<script>

	try {
		alert('Начало блока try');
		alert('ошибка' + error1);
		alert('Конец блока try');
	}	catch (err) {
		alert('ошибка!');
		alert(err.name);
		alert(err.message);
		alert(err.stack);


		//alert('Данное сообщение не будет выведено');

	}
</script>